
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionSoap {


    /**
     * 
     * @param stringUser
     * @param stringTransactionType
     * @return
     *     returns web.GroupOfServices
     */
    @WebMethod
    @WebResult(name = "TransactionUserAndType", partName = "TransactionUserAndType")
    @Action(input = "http://web/TransactionSoap/readAllRequest", output = "http://web/TransactionSoap/readAllResponse")
    public GroupOfServices readAll(
        @WebParam(name = "StringUser", partName = "StringUser")
        String stringUser,
        @WebParam(name = "StringTransactionType", partName = "StringTransactionType")
        String stringTransactionType);

}
