//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.25 at 09:09:25 AM IST 
//


package transaction.services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the transaction.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: transaction.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateRemarksResponse }
     * 
     */
    public UpdateRemarksResponse createUpdateRemarksResponse() {
        return new UpdateRemarksResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link Transactions }
     * 
     */
    public Transactions createTransactions() {
        return new Transactions();
    }

    /**
     * Create an instance of {@link FilterByReceiverResponse }
     * 
     */
    public FilterByReceiverResponse createFilterByReceiverResponse() {
        return new FilterByReceiverResponse();
    }

    /**
     * Create an instance of {@link NewTransactionresponse }
     * 
     */
    public NewTransactionresponse createNewTransactionresponse() {
        return new NewTransactionresponse();
    }

    /**
     * Create an instance of {@link FilterByAmountResponse }
     * 
     */
    public FilterByAmountResponse createFilterByAmountResponse() {
        return new FilterByAmountResponse();
    }

    /**
     * Create an instance of {@link FilterByReceiverRequest }
     * 
     */
    public FilterByReceiverRequest createFilterByReceiverRequest() {
        return new FilterByReceiverRequest();
    }

    /**
     * Create an instance of {@link DeleteByRangeOfTransactionRequest }
     * 
     */
    public DeleteByRangeOfTransactionRequest createDeleteByRangeOfTransactionRequest() {
        return new DeleteByRangeOfTransactionRequest();
    }

    /**
     * Create an instance of {@link FilterBySenderResponse }
     * 
     */
    public FilterBySenderResponse createFilterBySenderResponse() {
        return new FilterBySenderResponse();
    }

    /**
     * Create an instance of {@link FilterBySenderRequest }
     * 
     */
    public FilterBySenderRequest createFilterBySenderRequest() {
        return new FilterBySenderRequest();
    }

    /**
     * Create an instance of {@link DeleteByRangeOfTransactionResponse }
     * 
     */
    public DeleteByRangeOfTransactionResponse createDeleteByRangeOfTransactionResponse() {
        return new DeleteByRangeOfTransactionResponse();
    }

    /**
     * Create an instance of {@link NewTransactionrequest }
     * 
     */
    public NewTransactionrequest createNewTransactionrequest() {
        return new NewTransactionrequest();
    }

    /**
     * Create an instance of {@link UpdateRemarksRequest }
     * 
     */
    public UpdateRemarksRequest createUpdateRemarksRequest() {
        return new UpdateRemarksRequest();
    }

    /**
     * Create an instance of {@link FilterByAmountRequest }
     * 
     */
    public FilterByAmountRequest createFilterByAmountRequest() {
        return new FilterByAmountRequest();
    }

}
