//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.28 at 06:45:55 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.transaction", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package transaction.services;
